### ISSUE TITLE
Active server is 0

### ISSUE THREAD

**Issue by senthilsivanath** [HangfireIO/Hangfire#223] opened 2014-10-03 17:40 UTC
Web server is up and running yet hangfire shows active servers as 0 and background tasks are not processed.

**Comment by CrazyPyro** [comment] 2015-06-23 18:14
Looks like this is still a current problem: http://stackoverflow.com/questions/30970199/hangire-has-no-active-servers
I can reproduce this myself, but haven't been able to distill the root cause.

**Comment by S3NS4Ti0N** [comment] 2015-06-23 18:20
can confirm the issue from here too.

**Comment by CrazyPyro** [comment] 2015-06-24 00:41
Ok. My problem was specifically that I was running multiple applications *in the same app pool* so the standard "machinename:PID" naming scheme was not unique.  But each app was pointed to its own separate database.  So there was a race on startup/deploy and only one of the apps got to claim the single BackgroundJobServer as its own.

The [docs](http://docs.hangfire.io/en/latest/background-processing/running-multiple-server-instances.html) *do* say this: "Since the defaults values provide uniqueness only on a process level, you should to handle it manually, if you want to run different server instances inside the same process"

I'd suggest the some text like the following be added: "Since IIS app pools use a single process,  this situation includes multiple applications running under the same app pool."

Furthermore, when I attempted to implement the change suggested in the doc, I was stymied by the maxlength problem mentioned in [this comment](http://docs.hangfire.io/en/latest/background-processing/running-multiple-server-instances.html#comment-2067804250)   I know that problem will be fixed in a future version, but I think the doc should mention this at least in the meantime.  Perhaps use something shorter than a GUID for uniqueness?  (In my case, I used the application's name.)

**Comment by odinserj** [comment] 2015-07-22 08:55
Hi there! Background job server instances now (since [1.5.0-beta1](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.0-beta1)) use GUID-based unique identifiers for each instance, so there is no need to set any magic server names.

**Closed by odinserj** 2015-07-22 08:55 UTC

**Comment by Krishloozer** [comment] 2017-05-11 08:01
@odinserj , Hi, the issue still exist in the latest updated version 1.6.3 - Initially it is showing the server count but after some time the count becomes zero don't know why ?
In my case each application uses separate application pool but still getting the issue.

**Comment by andreasringdal** [comment] 2018-01-05 07:50
We experience this issue as well. Run Hangfire 1.6.17 with multiple instances in separate windows services and separate databases. Initially the server count is set to 1 for each database, but after a while the server count is set to 0. Resetting the service brings the counters back.
Jobs are processed fine whiel the server count is 0.

**Comment by odinserj** [comment] 2018-01-06 11:35
@andreasringdal, ensure all the clocks on your machines are synchronised and you are using `ServerTimeout`s, which values are at least 15 minutes to handle clock skew. With the upcoming changes in #1082, servers will detect that they are removed, and will be restarted automatically with the new id.

**Comment by andreasringdal** [comment] 2018-01-08 12:43
All hangfireinstances are running on separate instances on the same server.
ServerTimeout is not set (using default)

Including code used to start
```
if (_jobServer != null) return;

                _scope = _kernel.BeginScope();
                _logProvider = new WindsorLogProvider(_kernel.Resolve<ILogger>(), Environment.UserInteractive ? new ColouredConsoleLogProvider() : null);

                var config = GlobalConfiguration.Configuration;
                config.UseLogProvider(_logProvider);
                config.UseSqlServerStorage("AdmmitScheduler",new SqlServerStorageOptions { CommandBatchMaxTimeout = TimeSpan.FromMinutes(25) });
                var options = new BackgroundJobServerOptions
                {
                    Activator = new WindsorJobActivator(_kernel),
                    FilterProvider = new AdmMitJobFilterProvider(),
                    WorkerCount = Math.Max(1, Settings.Default.SchedulerWorkerCount),
                    ServerCheckInterval = TimeSpan.FromSeconds(15),                                        
                    Queues = new[]
                    {
                        JobHelper.LocalQueueName,
                        nameof(JobPriority.B).ToLowerInvariant(),
                        nameof(JobPriority.C).ToLowerInvariant(),
                        nameof(JobPriority.D).ToLowerInvariant(),
                        nameof(JobPriority.E_Urgent).ToLowerInvariant(),
                        nameof(JobPriority.F).ToLowerInvariant(),
                        nameof(JobPriority.G_Higher).ToLowerInvariant(),
                        nameof(JobPriority.H).ToLowerInvariant(),
                        nameof(JobPriority.I_High).ToLowerInvariant(),
                        nameof(JobPriority.J).ToLowerInvariant(),
                        nameof(JobPriority.K).ToLowerInvariant(),
                        nameof(JobPriority.L).ToLowerInvariant(),
                        nameof(JobPriority.M_Default).ToLowerInvariant(),
                        "default",      //Included to cach jobs created without priority set. Queues are sorted alphabetically. This will be included prior to all other Queues
                        nameof(JobPriority.N).ToLowerInvariant(),
                        nameof(JobPriority.O).ToLowerInvariant(),
                        nameof(JobPriority.P).ToLowerInvariant(),
                        nameof(JobPriority.Q_Low).ToLowerInvariant(),
                        nameof(JobPriority.R).ToLowerInvariant(),
                        nameof(JobPriority.S).ToLowerInvariant(),
                        nameof(JobPriority.T).ToLowerInvariant(),
                        nameof(JobPriority.Z_Lowest).ToLowerInvariant()
                    }
                };

                var maintenance = new CacheMaintenanceProcess(
                    Settings.Default.SchedulerAccountClientId,
                    Settings.Default.SchedulerAccountUserId,

                    _kernel.Resolve<IDbContextFactory<AdmmitEntities>>(),
                    _kernel.ResolveAll<ILookupValueCache>());

                maintenance.PerformPreBootMaintenance();

                _jobServer = new BackgroundJobServer(options, _storage, new[] { maintenance });
```

**Comment by andreasringdal** [comment] 2018-01-16 13:42
@odinserj I had a look at the code. 
Is it correct that a if a server has been removed from the server table due to timeout, it will not be added to the table again even when jobs are running?

Will updating the Heartbeath method in SqlServerConnection.cs to insert server if not exist fix this or will it introduce other issues?
