### ISSUE TITLE
Error when creating a new job from existing job 1.7.28

### ISSUE THREAD

**Issue by half-naan** [HangfireIO/Hangfire#2003] opened 2022-02-24 17:22 UTC
I am trying to resolve an issue where all the jobs are executed after server reboot.  It is not desired behavior for us given that the timing of jobs is very important. I stumbled across this [post ](https://github.com/HangfireIO/Hangfire/issues/620#issuecomment-753953995) and tried to re-create the jobs at startup. Unfortunately, I am getting an error message with 1.7.28 that the method params and the argument params do not match.  Even though they match, please see the attached screenshot. 

Thanks!
```csharp
using (var connection = JobStorage.Current.GetConnection())
{
	foreach (var recurringJob in connection.GetRecurringJobs())
	{
		var jobTimeZone = TimeZoneInfo.FindSystemTimeZoneById(recurringJob.TimeZoneId) ?? TimeZoneInfo.Utc;
		var name = recurringJob.Id;

		RecurringJob.RemoveIfExists(recurringJob.Id);

		var manager = new RecurringJobManager();
		var methodParameters = recurringJob.Job.Method.GetParameters().Length;
		var jobArgs = recurringJob.Job.Args.Count;
		var job = new Hangfire.Common.Job(recurringJob.Job.Type, recurringJob.Job.Method, recurringJob.Job.Args);

		manager.AddOrUpdate(name, job, recurringJob.Cron, jobTimeZone, recurringJob.Queue);
	}
}
```
![image](https://user-images.githubusercontent.com/57302140/155574688-f0b3ae26-6c72-4d10-ab36-559421040de3.png)

**Comment by alcalin** [comment] 2024-12-05 20:51
Hi, this worked for me: 
```
public class SkipMissedRecurringJobsAttribute : JobFilterAttribute, IServerFilter
{
    public void OnPerforming(PerformingContext filterContext)
    {
        var jobData = filterContext.Connection.GetJobData(filterContext.BackgroundJob.Id);
        if (jobData.CreatedAt < DateTime.UtcNow.AddMinutes(-5))
        {
            filterContext.Canceled = true; 
        }
    }

    public void OnPerformed(PerformedContext filterContext) { }
}
```

**Comment by odinserj** [comment] 2024-12-06 10:56
Omg, thanks for pinging, this should be fixed. The problem is that the `Job`'s constructor overload takes `params object[]` parameter for `args`, so when array is passed, it's considered as the first argument, resulting in the exception. Another constructor overload should be added that uses the `object[]` parameter instead for this use case.

**Comment by odinserj** [comment] 2024-12-09 10:17
The following line in the original question:

```csharp
var job = new Hangfire.Common.Job(recurringJob.Job.Type, recurringJob.Job.Method, recurringJob.Job.Args);
```

Should be changed wit the `ToArray` call:

```csharp
var job = new Hangfire.Common.Job(recurringJob.Job.Type, recurringJob.Job.Method, recurringJob.Job.Args.ToArray());
```

That `Job` constructor overload takes `params object[]` as the last argument, while the `Args` property returns `IReadOnlyList<object>`. So the whole list is passed as a single argument, due to the type mismatch.

I think the best way to handle this inconsistency would be to change the parameter type of that `Job` constructor to `params IReadOnlyList<object>`, since the newest C# compilers allow doing this. However, this is a breaking change.

**Closed** 2024-12-09 10:29 UTC
Labels: t: bug, a: core
