### ISSUE TITLE
Enqueued jobs are not being processing

### ISSUE THREAD

**Issue by oguzhantopcu** [HangfireIO/Hangfire#1257] opened 2018-09-02 07:49 UTC
_Problem: Time to time, enqueued jobs are not being processing until I restart the application._

There are many logs like this:
```
Sep 01 20:44:26 fed.localdomain my-app[16486]: [20:44:26 DBG] Hangfire.PostgreSql.ExpirationManager: Removing outdated records from table 'counter'...
Sep 01 20:44:27 fed.localdomain my-app[16486]: [20:44:27 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:27 fed.localdomain my-app[16486]: [20:44:27 DBG] Hangfire.PostgreSql.ExpirationManager: Removing outdated records from table 'counter'...
Sep 01 20:44:27 fed.localdomain my-app[16486]: [20:44:27 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:28 fed.localdomain my-app[16486]: [20:44:28 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:28 fed.localdomain my-app[16486]: [20:44:28 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:29 fed.localdomain my-app[16486]: [20:44:29 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:29 fed.localdomain my-app[16486]: [20:44:29 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:30 fed.localdomain my-app[16486]: [20:44:30 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:30 fed.localdomain my-app[16486]: [20:44:30 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:31 fed.localdomain my-app[16486]: [20:44:31 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:31 fed.localdomain my-app[16486]: [20:44:31 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:32 fed.localdomain my-app[16486]: [20:44:32 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:32 fed.localdomain my-app[16486]: [20:44:32 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:34 fed.localdomain my-app[16486]: [20:44:34 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:34 fed.localdomain my-app[16486]: [20:44:34 INF] Hangfire.PostgreSql.ExpirationManager: Removed 707 outdated record(s) from 'counter' table.
Sep 01 20:44:35 fed.localdomain my-app[16486]: [20:44:35 INF] Hangfire.PostgreSql.ExpirationManager: Removed 1000 outdated record(s) from 'counter' table.
Sep 01 20:44:35 fed.localdomain my-app[16486]: [20:44:35 DBG] Hangfire.PostgreSql.ExpirationManager: Removing outdated records from table 'job'...
```

There is an error like this in the logs.

```
Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt #1) in 00:00:00 seconds.
Sep 02 02:47:15 fed.localdomain my-app[16486]: System.TimeoutException: SetRangeInHash experienced timeout while trying to execute transaction
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.PostgreSql.PostgreSqlConnection.SetRangeInHash(String key, IEnumerable`1 keyValuePairs)
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.Server.RecurringJobScheduler.TryScheduleJob(JobStorage storage, IStorageConnection connection, String recurringJobId, IReadOnlyDictionary`2 recurringJob)
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.Server.RecurringJobScheduler.<>c__DisplayClass8_0.<Execute>b__0(IStorageConnection connection)
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock(JobStorage storage, Action`1 action)
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
Sep 02 02:47:15 fed.localdomain my-app[16486]:    at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```

I am using hangfire  with postgresql, and package versions are:
```

<PackageReference Include="HangFire" Version="1.6.20" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.6.20" />
    <PackageReference Include="hangfire.autofac" Version="2.3.1" />
    <PackageReference Include="Hangfire.Core" Version="1.6.20" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.4.8.2" />

```
my hangfire configuration

```
app.UseHangfireServer(new BackgroundJobServerOptions {WorkerCount = 50});
            app.UseHangfireServer(new BackgroundJobServerOptions
            {
                WorkerCount = 2,
                Queues = new[] {BackgroundQueue.Invoice}
            });

            app.UseHangfireDashboard(
                "/hangfire",
                new DashboardOptions
                {
                    Authorization = new[]
                    {
                        new HangfireAuthFilter(serviceProvider.GetService<ILogger<HangfireAuthFilter>>())
                    }
                }
            );

            services.AddHangfire(x => x.UsePostgreSqlStorage(GetConnectionString()));

```

There is a bigger issue that triggered by this problem, too. Once the enqueued jobs reached over 50-60k, job processing starting perform very slowly, even though I restart the application hangfire becoming  so slow for processing these enqueued jobs until enqueued job count is decreased to reasonable amount.

![hangfire_sucks](https://user-images.githubusercontent.com/2956166/44953382-6311a780-ae9d-11e8-9644-02682f06b01d.png)
![hangfire_sucks2](https://user-images.githubusercontent.com/2956166/44953383-6311a780-ae9d-11e8-8a94-e3f55a524ee0.png)

**Comment by Deyvisonr0** [comment] 2018-09-03 03:37
Facing same problem here whit asp.net core 2.1

**Comment by pielegacy** [comment] 2018-09-15 05:33
I am getting the same issue and this is stopping us from pushing our application into production, there’s are also multiple duplicates of this issue sitting in Github without any form of acknowledgment from contributors to the project. Are there any resources available that could help with this?

**Comment by oguzhantopcu** [comment] 2018-10-04 10:12
I have been getting this issue time to time since I have posted here. Did not solved. I have tried deleting whole hangfire scheme 1 week ago, I have faced the same issue again today. Well, I will switch to alternatives.

**Comment by pielegacy** [comment] 2018-10-04 10:14
As an update following up to this, the problem was being caused by me trying to run database migrations programmatically as a hangfire job. Hangfire didn't like this and so it resulted in the never closing threads/worker processes. Not exactly a fix but just additional information

**Comment by NeenuSunil** [comment] 2019-06-13 04:07
Is there any update on this issue?

**Comment by odinserj** [comment] 2019-06-13 14:35
Original problem is likely to be caused by Hangfire.PostgreSql job storage, and it's better to raise a question in its repository to understand why there was a timeout. For other questions – it's hard to understand what happens without configuration, versions, dashboard screenshots and logs.

**Comment by oguzhantopcu** [comment] 2019-06-13 15:19
My problem was `InvisibilityTimeout`. 

I hit to a .net core bug happens randomly when a socket closed on linux. Some socket close operations was locking the thread randomly. Once the job thread locked, job process is not ending. Once the default invisibility timeout passed, job is becoming unvisible **although that hangfire thread still in use** . Once hangfire queue limit filled with locked threads, system was stopping executing new jobs.

I think this is a design issue should be solved.

**Comment by odinserj** [comment] 2019-06-13 15:53
@oguzhantopcu thanks for update on this! I think the problem is also related to distributed lock implementation in that storage, so changes are required. Also better documentation is required for storage abstractions together with some "quality" metric for a storage implementation. I've created #1296 with some coverage on this issue, but understand more details needed.

**Closed** 2019-06-13 15:53 UTC
Labels: t: question
