### ISSUE TITLE
Hangfire should continue to send heartbeats until all jobs have completed during shutdown.

### ISSUE THREAD

**Issue by anhaehne** [HangfireIO/Hangfire#2235] opened 2023-07-05 12:56 UTC
We have have some long running jobs and whenever we deploy a new version of our application (asp.net core) we want to do a graceful shutdown of our application.

Right now hangfire is correctly waiting for running jobs and also not accepting any new jobs when a sigterm was sent to the application.
The problem is that hangfire also stops sending heartbeats so other instances of the application think the jobs where abandoned.

Setting the sliding invisibility timout higher should work around this issue but the correct behavior would be for hangfire to continue sending heartbeats until no more jobs are being processed.

**Comment by odinserj** [comment] 2023-07-06 10:26
Duplicate of #2233

**Closed by odinserj** 2023-07-06 10:26 UTC
