### ISSUE TITLE
Deadlock with SetJobParameter

### ISSUE THREAD

**Issue by johnhwright** [HangfireIO/Hangfire#1743] opened 2020-09-29 19:49 UTC
**Hanfire.Core**: 1.7.11
**Hangfire.SqlServer**: 1.7.11

We have a number of cases where we set a special job parameter along side the normal creation of a job.

We use autofac to build out container, the job client looks like:
```
builder.Register(ctx => new SqlServerStorage(ctx.Resolve<IConnectionStrings>().Hangfire, new SqlServerStorageOptions
{
    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
    QueuePollInterval = TimeSpan.Zero,
    UseRecommendedIsolationLevel = true,
    UsePageLocksOnDequeue = true,
    DisableGlobalLocks = true,
    PrepareSchemaIfNecessary = false,
})).AsSelf();
builder.Register(ctx => new BackgroundJobClient(ctx.Resolve<SqlServerStorage>())).As<IBackgroundJobClient>();
```

We then have usages like:
```
{
        private IBackgroundJobClient BackgroundJobClient { get; }
        private SqlServerStorage SqlServerStorage { get; }

        public ClassA(IBackgroundJobClient backgroundJobClient, SqlServerStorage sqlServerStorage)
        {
            BackgroundJobClient = backgroundJobClient;
            SqlServerStorage = sqlServerStorage;
        }

        public string DoWork<T>(string param, Expression<Func<T, Task>> methodCall)
        {
            var jobId = BackgroundJobClient.Enqueue(methodCall);
            SqlServerStorage.GetConnection().SetJobParameter(jobId, "DoWorkParam", $"\"{param}\"");
            return jobId;
        }
}
```

When this is called multiple times across different threads we seem to deadlock on the parameter table:
![image](https://user-images.githubusercontent.com/11820009/94607733-274e9500-0251-11eb-9a05-f7a7a24ffa51.png)

Is there a different approach we should be taking for setting these external parameters?

**Comment by odinserj** [comment] 2020-09-30 10:51
Thank you for your investigation. Could you try to upgrade to version 1.7.13 and check whether the problem is gone? Unfortunately latest version 1.7.14 have improvements rolled back due to another problem, but at least we'll be able to ensure everything can be resolved by the new query.

**Comment by johnhwright** [comment] 2020-09-30 15:31
@odinserj That's very interesting. I unfortunately misread the first time and updated to 1.7.14 and things were actually even worse with 2 different deadlocks, one now involving the JobQueue as well. 

But after installing the .13 as you specified we can no longer seem to reproduce the deadlock. Though as you mentioned, seems like .13 has some problems of its own.

Guessing the next release will be the magic.

**Comment by odinserj** [comment] 2020-10-01 07:48
I'm curious whether you've collected that deadlock related to `JobQueue` and could you post here your configuration logic related to Hangfire? I'm afraid there were no changes related to queries for the `JobQueue` table.

**Comment by johnhwright** [comment] 2020-10-01 18:12
I was mistaken, the logs were just showing that connection also contained a page lock on the JobQueue table, but the deadlock still revolves around the same JobParameter key lock.

We've only just been beginning to expand our use so our configuration for the server setup is still pretty basic:
```
public static void ConfigureHangfire(IAppBuilder app, IContainer container)
{
    GlobalConfiguration.Configuration.UseActivator(new AutofacJobActivator(container, false));
    GlobalConfiguration.Configuration.UseSerilogLogProvider();

    app.UseHangfireAspNet(GetHangfireServers);
    app.UseHangfireDashboard("/dashboard", GetDashboardOptions());
}

private static IEnumerable<IDisposable> GetHangfireServers()
{
    GlobalConfiguration.Configuration
        .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
        .UseSimpleAssemblyNameTypeSerializer()
        .UseRecommendedSerializerSettings()
        .UseSqlServerStorage(Settings.ConnectionStrings.Hangfire, new SqlServerStorageOptions
        {
            CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
            SlidingInvisibilityTimeout = TimeSpan.FromMinutes(10),
            QueuePollInterval = TimeSpan.Zero,
            UseRecommendedIsolationLevel = true,
            UsePageLocksOnDequeue = true,
            DisableGlobalLocks = true,
            PrepareSchemaIfNecessary = true,
        })
        .UseFilter(new AutomaticRetryAttribute { Attempts = 4, DelaysInSeconds = new[] { 120, 300, 3600, 86400 }, LogEvents = true })
        .UseFilter(new LogActivityFilterAttribute())
        .UseFilter(new ProlongExpirationTimeAttribute());

    yield return new BackgroundJobServer(GetBackgroundServerOptions());
}
```

And the deadlock still occurs even when no queues are registered for processing, so definitely seems to just be the client

Looking forward to that next release!

Thanks

**Closed** 2020-10-02 11:03 UTC
Labels: a: sql-server, t: bug
