### ISSUE TITLE
Getting warning messages about Newtonsoft.Json 5.0.0

### ISSUE THREAD

**Issue by Gillardo** [HangfireIO/Hangfire#947] opened 2017-07-20 15:47 UTC
Since i have updated to the latest version i am getting warning messages in VS saying that Hangfire.Core depends on Newtonsoft 5.0.0 and this cannot be resolved

![image](https://user-images.githubusercontent.com/7406381/28426456-15093cd4-6d6b-11e7-8ea8-ebc1a27933a6.png)

Any reason why you are using such as old version of newtonsoft as well??

**Comment by tjrobinson** [comment] 2017-09-05 11:14
Does adding an assembly binding redirect in the `App.config` or `Web.config` help?

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by tjrobinson** [comment] 2017-09-05 15:12
I was having this problem, but it was only preventing NCrunch from building my project correctly. I did the following and the problem seems to have gone away (not sure which change fixed it):

- Added `Newtonsoft.Json` (9.0.1 in my case) to the project rather than it being referenced via other project dependencies
- Added `NU1603` to the `NoWarn` list for my `PackageReference` to `Hangfire`:

```
    <PackageReference Include="Hangfire" Version="1.6.14">
      <NoWarn>NU1603</NoWarn>
    </PackageReference>
```

**Comment by tjrobinson** [comment] 2017-09-13 13:14
Update: I've run into this again and upgrading from Hangfire `1.6.14` to `1.6.16` didn't help, but adding `Newtonsoft.Json (9.0.1 in my case) to the project rather than it being referenced via other project dependencies did resolve the issue. I didn't use `NoWarn`.

**Comment by ergwun** [comment] 2017-10-25 04:42
Duplicate of #973.

**Comment by j3rm** [comment] 2017-12-21 15:28
This must be an issue in the 1.6.17 build, I rolled back to 1.6.16 and the problem went away.
That has to be the easiest solution.

**Closed** 2017-12-25 17:20 UTC
