### ISSUE TITLE
Why I can't specify the table prefix? 

### ISSUE THREAD

**Issue by sk29110** [HangfireIO/Hangfire#968] opened 2017-08-16 21:05 UTC
I am tying to find a way to set prefix for all tables used in the hangfire. 
I saw the following issue about the custom schema but was wondering if prefix for tables already implemented.
If not I want to ask why this is not implemented yet although all the table names are so general. Do you always except to have one dedicated database for hangfire?

https://github.com/HangfireIO/Hangfire/issues/432

**Comment by odinserj** [comment] 2017-08-17 12:24
Why can't you use multiple schemas for multiple Hangfire installations?

**Comment by sk29110** [comment] 2017-08-17 19:33
Sorry I never use the schema( always use default schema ) before I didn't know adding schema in the same database was a way to go.

Thanks!

**Comment by odinserj** [comment] 2017-08-18 08:53
Since you are fine with dedicated schemas, I'm closing this issue.

**Closed by odinserj** 2017-08-18 08:53 UTC
Labels: a: sql-server, t: feature-request

**Comment by sheldmandu** [comment] 2018-11-07 22:49
hi @odinserj is it feasable for you to implement a table prefix in the near future?  That would be really beneficial as it would enable all the job scheduling data to be in the same database as the rest of the application so it can be backed up, migrated, replicated, etc as a single unit.  The current problem is because the tables are named so generally they are likely to (and do in our case) clash with tables used in the application domain.

**Comment by sheldmandu** [comment] 2018-11-07 22:53
@odinserj to clarify further, in our case part of the issue is the framework on which the application is based which doesn't work particularly well with multiple databases or multiple schemas and we were looking to surface some of the information directly out of the tables into the application.

**Comment by burningice2866** [comment] 2018-11-07 22:57
@sheldmandu just out of curiosity - how can an application not work well with multiple schemas? Isn't the schema tied to the user used for connection to the database and therefor transparent to the application?

**Comment by sheldmandu** [comment] 2018-11-08 01:37
@odinserj We're using DevExpress XAF with XPO as the ORM and the connection to the DB is made with a single user in a standard way the framework handles it.  We want to surface some of the information about the jobs in the application and by far the easiest way to do so is using XPO so that UI is generated over the objects automatically.  The alternative way is to add the objects from the Hangfire domain as NonPersistent and get the UI to generate over those.  It would be great to be able to specify a table prefix like "Scheduler" or even "Hangfire" and not have to deal with separate schemas and finding ways around that.

**Comment by sheldmandu** [comment] 2018-11-09 05:32
@odinserj I did a bit more research and looks like I can map objects to multiple schemas so will be all good as it is.
