### ISSUE TITLE
Inefficient String Concatenation 

### ISSUE THREAD

**Issue by kfrancis** [HangfireIO/Hangfire#2486] opened 2024-12-16 20:02 UTC
Getting these notices on AppInsights, thought it worth sharing.

Hangfire.AspNetCore v1.8.14
Hangfire.SqlServer v1.8.14

- [ ] `SqlServerJobQueue.FetchJob` - Inefficient String Concatenation
- [ ] `SqlServerStorage.CreateAndOpenConnection` - Inefficient String Concatenation

## `SqlServerJobQueue.FetchJob` - Inefficient String Concatenation

Description: Excessive string concatenation is causing lots of allocations and CPU consumption.

Current condition: 6% of your Memory was spent in ```````````String.Concat``````````` called from ```````````Hangfire.SqlServer.SqlServerJobQueue.FetchJob```````````. We expected this value to be <1%.

Recommendations: Consider using cheaper alternatives such as `String.Join` or a `StringBuilder` instead.

Call Stack:

0. Type System.String
1. system.private.corelib.il!System.String.Concat(class System.String,class System.String,class System.String)
2. hangfire.sqlserver!Hangfire.SqlServer.SqlServerJobQueue+<>c__DisplayClass14_0.<FetchJob>b__0(class System.Data.Common.DbConnection)
3. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.UseConnection(class System.Data.Common.DbConnection,class System.Func`2<class System.Data.Common.DbConnection,!!0>)
4. hangfire.sqlserver!Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingSlidingInvisibilityTimeout(class System.String[],value class System.Threading.CancellationToken)
5. hangfire.core!Hangfire.Server.Worker.Execute(class Hangfire.Server.BackgroundProcessContext)
6. hangfire.core!Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(value class System.Guid,class System.Object)
7. hangfire.core!Hangfire.Processing.BackgroundExecution.Run(class System.Action`2<value class System.Guid,class System.Object>,class System.Object)

## `SqlServerStorage.CreateAndOpenConnection` - Inefficient String Concatenation

Description: Excessive string concatenation is causing lots of allocations and CPU consumption.

Current condition: 3% of your Memory was spent in ```````````String.Concat``````````` called from ```````````Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection```````````. We expected this value to be <1%.

Recommendations: Consider using cheaper alternatives such as `String.Join` or a `StringBuilder` instead.

Call Stack:

0. Type System.String
1. system.private.corelib.il!System.String.Concat(class System.String,class System.String)
2. microsoft.data.sqlclient!Microsoft.Data.Common.ADP.IsEndpoint(class System.String,class System.String)
3. microsoft.data.sqlclient!Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(class System.String)
4. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
5. hangfire.sqlserver!Hangfire.SqlServer.SqlServerStorage.UseConnection(class System.Data.Common.DbConnection,class System.Func`2<class System.Data.Common.DbConnection,!!0>)
6. hangfire.core!Hangfire.Server.ServerJobCancellationToken.TryCheckJobIsAborted(class Hangfire.Storage.IStorageConnection)
7. hangfire.core!Hangfire.Server.ServerJobCancellationToken.CheckAllCancellationTokens(class System.String,class Hangfire.Storage.IStorageConnection,value class System.Threading.CancellationToken)
8. hangfire.core!Hangfire.Server.ServerJobCancellationWatcher.Execute(class Hangfire.Server.BackgroundProcessContext)
9. hangfire.core!Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(value class System.Guid,class System.Object)

**Comment by odinserj** [comment] 2024-12-17 05:38
SqlServerJobQueue.FetchJob concatenations caused by Dapper and its implementation of generating SQL when using dynamic parameter count. Recent versions switched to ADO.NET-based implementation, and the resulting query is fully cached, please try running this on 1.8.17 or newer when available.

SqlServerStorage.CreateAndOpenConnection concatenations are caused by the implementation of Microsoft.Data.SqlClient (its [`ADP.IsEndpoint` class](https://github.com/dotnet/SqlClient/blob/44cfeddd0543e0ccbcf613e98e5887a6eac67541/src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs#L796)), so out of scope of this repository.

So I'm closing this as already completed.

**Closed by odinserj** 2024-12-17 05:38 UTC
