### ISSUE TITLE
Timeout and sql connection is not disposed

### ISSUE THREAD

**Issue by ravenet** [HangfireIO/Hangfire#986] opened 2017-09-04 01:58 UTC
HI,

 A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - The handle is invalid.)

when it is connect to server where it can not reached within  given time, it is throw error and thereafter, we are getting whole db server can not run due to this critical case.

Please let me know how to resolve.

Thank you

**Comment by odinserj** [comment] 2017-09-09 15:25
Please list here all the Hangfire package versions you are using, as well as some information about your runtime (.NET Core or .NET Framework version). May be a duplicate of the #965 issue.

**Closed** 2019-04-17 12:31 UTC
Labels: t: question
